### ISSUE TITLE
payment_intent in Tag 19

### ISSUE THREAD

**Issue by ChimexOji** [SteinOveHelset/nordichomes#2]
payment_intent no longer works after code is refractored in Tag 19 from Tag 18 in /order/views.py. It keeps displaying; "TypeError: Order() got an unexpected keyword argument 'payment_intent' ".
![payment-error](https://user-images.githubusercontent.com/86106859/218418987-93614d86-d0aa-4e94-bcc1-64d3ca1a6391.jpg)

**Comment by SteinOveHelset** [comment]
Yes, you need to add one more field to the order model:
payment_intent = models.CharField(max_length=255)
